spring:
  profiles: 
    active: dev
  timerName: exampleTimer
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
---
# mybatis:
#   mapper-locations: classpath:mapper/**/*.xml
#   configuration:
#     lazyLoadingEnabled: true
#     aggressiveLazyLoading: false
#     mapUnderscoreToCamelCase: true

spring:
  profiles: local
  task:
    fixedDelay: 1000
    name: localTask
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: vuetest
    password: vuetest
---
spring:
  profiles: dev
  task:
    fixedDelay: 5000
    name: devTask
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: vuetest
    password: vuetest
---
server:
  port: 3000


---
spring:
  mvc:
    static-path-pattern: /static/**
